name: LMSX Frontend CI

on:
  push:
    branches:
      - main

jobs:
  basic-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Show CI message
        run: echo "CI works succwqessfully"
